<?php
/** 
 * Magento CZ Module
 * 
 * NOTICE OF LICENSE 
 * 
 * This source file is subject to the Open Software License (OSL 3.0) 
 * that is bundled with this package in the file LICENSE.txt. 
 * It is also available through the world-wide-web at this URL: 
 * http://opensource.org/licenses/osl-3.0.php
 * If you did of the license and are unable to 
 * obtain it through the world-wide-web, please send an email 
 * to magentocz@gmail.com so we can send you a copy immediately. 
 * 
 * @copyright Copyright (c) 2014 GetReady s.r.o. (https://getready.cz)
 * 
 */ 
/** 
 * Česká pošta
 * 
 * @category Magentocz 
 * @package Magentocz_Ceskaposta
 * @author Jaromir Muller, jaromir.muller@getready.cz
 */
?>
<script type="text/javascript">
//<![CDATA[
  
  

  var Magentocz = Magentocz || {};
  Magentocz.Ceskaposta = Magentocz.Ceskaposta || {};
  Magentocz.Ceskaposta.importData = function () {    
    var buttonId = '<?php echo $this->getButtonId() ?>';
    var url = '<?php echo $this->getAjaxImportUrl() ?>';

    new Ajax.Request(url, {
      method : 'get',
      onSuccess : function(transport){
        if (transport.responseText){
            
          var result = JSON.parse(transport.responseText);
          console.log( result );

          if ( result.ok ) {
            $( buttonId ).addClassName( 'success' );
            $( buttonId ).update('<span><span>'+result.message+'</span></span>' );
            $( buttonId + '_count' ).remove();
          } else {
            $( buttonId ).addClassName('fail');
            $( buttonId ).update('<span><span>'+result.message+'</span></span>' );
          }          
        }
      }
    });
  }
//]]>
</script>
 
<?php echo $this->getButtonHtml() ?>
<span id="<?php echo $this->getButtonId() ?>_count">
<?php echo $this->__('Post database contains %s items', $this->countPosts()); ?>
</span>